import {
    Crown, TrendingUp, Settings2, HeartPulse, Megaphone,
    PenLine, Palette, Search, Target, BarChart3, Video, Users, Coffee
} from "lucide-react";

export const ROOMS = [
    // ── Row 1–2: Executive Floor ──────────────────────────────────────────────
    {
        id: "CEO Suite",
        nameAr: "جناح الرئيس التنفيذي",
        nameEn: "CEO Suite",
        icon: Crown,
        color: "text-amber-400",
        bg: "bg-amber-500/8",
        border: "border-amber-500/20",
        activeBorder: "border-amber-400/60",
        glow: "shadow-amber-500/20",
        colSpan: 2,
        rowSpan: 2,
    },
    {
        id: "Marketing Director",
        nameAr: "ماركتينج دايركتور",
        nameEn: "Marketing Director",
        icon: TrendingUp,
        color: "text-blue-400",
        bg: "bg-blue-500/8",
        border: "border-blue-500/20",
        activeBorder: "border-blue-400/60",
        glow: "shadow-blue-500/15",
        colSpan: 1,
        rowSpan: 1,
    },
    {
        id: "Operations Manager",
        nameAr: "أوبريشن مانجر",
        nameEn: "Operations",
        icon: Settings2,
        color: "text-slate-400",
        bg: "bg-slate-500/8",
        border: "border-slate-500/20",
        activeBorder: "border-slate-400/60",
        glow: "shadow-slate-500/15",
        colSpan: 1,
        rowSpan: 1,
    },
    {
        id: "HR Office",
        nameAr: "مكتب الـ HR",
        nameEn: "HR Office",
        icon: HeartPulse,
        color: "text-pink-400",
        bg: "bg-pink-500/8",
        border: "border-pink-500/20",
        activeBorder: "border-pink-400/60",
        glow: "shadow-pink-500/15",
        colSpan: 1,
        rowSpan: 2,
    },
    // Row 2 cont. (CEO Suite + HR Office still spanning)
    {
        id: "Marketing Room",
        nameAr: "غرفة الماركتينج",
        nameEn: "Marketing Room",
        icon: Megaphone,
        color: "text-violet-400",
        bg: "bg-violet-500/8",
        border: "border-violet-500/20",
        activeBorder: "border-violet-400/60",
        glow: "shadow-violet-500/15",
        colSpan: 2,
        rowSpan: 1,
    },
    // ── Row 3: Team Zones ─────────────────────────────────────────────────────
    {
        id: "Content Team",
        nameAr: "تيم الكونتنت",
        nameEn: "Content Team",
        icon: PenLine,
        color: "text-sky-400",
        bg: "bg-sky-500/8",
        border: "border-sky-500/20",
        activeBorder: "border-sky-400/60",
        glow: "shadow-sky-500/15",
        colSpan: 2,
        rowSpan: 1,
    },
    {
        id: "Art Team",
        nameAr: "تيم الآرت",
        nameEn: "Art Team",
        icon: Palette,
        color: "text-fuchsia-400",
        bg: "bg-fuchsia-500/8",
        border: "border-fuchsia-500/20",
        activeBorder: "border-fuchsia-400/60",
        glow: "shadow-fuchsia-500/15",
        colSpan: 2,
        rowSpan: 1,
    },
    {
        id: "SEO Team",
        nameAr: "تيم السيو",
        nameEn: "SEO Team",
        icon: Search,
        color: "text-lime-400",
        bg: "bg-lime-500/8",
        border: "border-lime-500/20",
        activeBorder: "border-lime-400/60",
        glow: "shadow-lime-500/15",
        colSpan: 1,
        rowSpan: 1,
    },
    // ── Row 4: General Rooms ──────────────────────────────────────────────────
    {
        id: "Strategy Room",
        nameAr: "غرفة الاستراتيجية",
        nameEn: "Strategy",
        icon: Target,
        color: "text-orange-400",
        bg: "bg-orange-500/8",
        border: "border-orange-500/20",
        activeBorder: "border-orange-400/60",
        glow: "shadow-orange-500/15",
        colSpan: 1,
        rowSpan: 1,
    },
    {
        id: "Analytics Hub",
        nameAr: "مركز التحليلات",
        nameEn: "Analytics",
        icon: BarChart3,
        color: "text-emerald-400",
        bg: "bg-emerald-500/8",
        border: "border-emerald-500/20",
        activeBorder: "border-emerald-400/60",
        glow: "shadow-emerald-500/15",
        colSpan: 1,
        rowSpan: 1,
    },
    {
        id: "Meeting Room",
        nameAr: "غرفة الاجتماعات",
        nameEn: "Meeting Room",
        icon: Video,
        color: "text-rose-400",
        bg: "bg-rose-500/8",
        border: "border-rose-500/20",
        activeBorder: "border-rose-400/60",
        glow: "shadow-rose-500/15",
        colSpan: 2,
        rowSpan: 1,
    },
    {
        id: "Client Zone",
        nameAr: "منطقة العملاء",
        nameEn: "Client Zone",
        icon: Users,
        color: "text-teal-400",
        bg: "bg-teal-500/8",
        border: "border-teal-500/20",
        activeBorder: "border-teal-400/60",
        glow: "shadow-teal-500/15",
        colSpan: 1,
        rowSpan: 1,
    },
    // ── Row 5: Lounge (full width) ────────────────────────────────────────────
    {
        id: "Lounge",
        nameAr: "الاستراحة",
        nameEn: "Lounge",
        icon: Coffee,
        color: "text-muted-foreground",
        bg: "bg-white/3",
        border: "border-white/8",
        activeBorder: "border-white/30",
        glow: "",
        colSpan: 5,
        rowSpan: 1,
    },
] as const;

export type RoomDef = typeof ROOMS[number];
export type RoomId = typeof ROOMS[number]["id"];

export type RoomMember = {
    userId: string;
    name: string;
    role: string;
    isCurrentUser: boolean;
};
