const {PrismaClient} = require('@prisma/client');
const p = new PrismaClient();
p.report.findFirst({
  where:{month:{contains:'2025-11'}},
  include:{client:true},
  orderBy:{createdAt:'desc'}
}).then(r => {
  if (!r) { console.log('NO REPORT FOUND'); return; }
  const m = JSON.parse(r.metrics);
  const fb = m.campaigns?.[0]?.platforms?.facebook;
  const ig = m.campaigns?.[0]?.platforms?.instagram;
  console.log('CLIENT:', r.client.name, '| MONTH:', r.month);
  console.log('FACEBOOK:', JSON.stringify(fb, null, 2));
  console.log('INSTAGRAM:', JSON.stringify(ig, null, 2));
  console.log('AUTO:', JSON.stringify(m._autoGenerated));
  p.$disconnect();
}).catch(e => console.error(e));
