const { Client } = require('ssh2');

const conn = new Client();
conn.on('ready', () => {
    // Write the script file on the server then run it
    conn.exec(`cat > /tmp/check_nov.mjs << 'EOF'
import { PrismaClient } from "/root/milaknight-os/node_modules/@prisma/client/index.js";
const prisma = new PrismaClient();
const reports = await prisma.report.findMany({
    where: { month: { startsWith: "2025-11" } },
    include: { client: { select: { name: true } } },
    orderBy: { createdAt: "desc" },
    take: 3
});
for (const r of reports) {
    const m = JSON.parse(r.metrics || "{}");
    const fb = m.campaigns?.[0]?.platforms?.facebook;
    const ig = m.campaigns?.[0]?.platforms?.instagram;
    console.log("=== Report:", r.id, "===");
    console.log("Client:", r.client.name);
    console.log("Month:", r.month);
    console.log("Status:", r.status);
    console.log("Created:", r.createdAt);
    console.log("FB:", JSON.stringify(fb));
    console.log("IG:", JSON.stringify(ig));
    console.log("AutoGenerated:", JSON.stringify(m._autoGenerated));
    console.log("");
}
await prisma.$disconnect();
EOF
node --input-type=module < /tmp/check_nov.mjs 2>&1`, { cwd: '/root/milaknight-os' }, (err, stream) => {
        if (err) { console.error(err); conn.end(); return; }
        stream.on('data', d => process.stdout.write(d.toString()));
        stream.stderr.on('data', d => process.stderr.write(d.toString()));
        stream.on('close', () => conn.end());
    });
}).connect({
    host: '72.61.162.106',
    port: 22,
    username: 'root',
    password: ';hdFJ6C1?YYc6FD8gdY2'
});
