const { Client } = require('ssh2');
const conn = new Client();

conn.on('ready', () => {
    const remoteScript = [
        "const { PrismaClient } = require('/root/milaknight-os/node_modules/@prisma/client');",
        "const prisma = new PrismaClient();",
        "async function check() {",
        "  try {",
        // Show full metrics content for all reports
        "    const reports = await prisma.$queryRawUnsafe('SELECT id, month, status, \"clientId\", metrics FROM \"Report\" ORDER BY \"createdAt\" DESC');",
        "    for (const r of reports) {",
        "      console.log('\\n=== REPORT', r.id, '| Month:', r.month, '| Status:', r.status, '===');",
        "      try {",
        "        const m = JSON.parse(r.metrics);",
        "        const platforms = m.campaigns?.[0]?.platforms || {};",
        "        console.log('  Platforms with data:', Object.keys(platforms).filter(k => platforms[k] !== null && platforms[k] !== undefined));",
        "        console.log('  Summary preview:', (m.summary || '').substring(0, 150));",
        "        console.log('  _autoGenerated:', JSON.stringify(m._autoGenerated));",
        "      } catch(e) { console.log('  PARSE ERROR:', e.message); }",
        "    }",
        // Check action plans
        "    const actionPlans = await prisma.$queryRawUnsafe('SELECT ap.id, ap.month, ap.status, c.name as client_name, COUNT(ai.id)::int as items FROM \"ActionPlan\" ap LEFT JOIN \"Client\" c ON c.id = ap.\"clientId\" LEFT JOIN \"ActionItem\" ai ON ai.\"actionPlanId\" = ap.id GROUP BY ap.id, ap.month, ap.status, c.name ORDER BY ap.\"createdAt\" DESC LIMIT 10');",
        "    console.log('\\n=== RECENT ACTION PLANS ===');",
        "    console.log(JSON.stringify(actionPlans, null, 2));",
        // Check services
        "    const services = await prisma.$queryRawUnsafe('SELECT id, name, \"nameAr\", \"isActive\", price FROM \"Service\" LIMIT 20');",
        "    console.log('\\n=== SERVICES ===');",
        "    console.log(JSON.stringify(services, null, 2));",
        // Check insights cron status
        "    const insights = await prisma.$queryRawUnsafe('SELECT \"clientId\", type, \"createdAt\", LENGTH(content)::int as content_len FROM \"ClientInsight\" ORDER BY \"createdAt\" DESC LIMIT 10');",
        "    console.log('\\n=== RECENT CLIENT INSIGHTS ===');",
        "    console.log(JSON.stringify(insights, null, 2));",
        "    await prisma.$disconnect();",
        "  } catch(e) { console.error('FAILED:', e.message); await prisma.$disconnect(); process.exit(1); }",
        "}",
        "check();"
    ].join('\n');

    conn.sftp((sftpErr, sftp) => {
        if (sftpErr) { console.error('SFTP error:', sftpErr); conn.end(); return; }
        const remotePath = '/tmp/mk_report_check.js';
        const stream = sftp.createWriteStream(remotePath);
        stream.on('close', () => {
            sftp.end();
            conn.exec(`cd /root/milaknight-os && node ${remotePath}`, (err, execStream) => {
                if (err) { console.error('Exec error:', err); conn.end(); return; }
                execStream.on('data', d => process.stdout.write(d.toString()));
                execStream.stderr.on('data', d => process.stderr.write(d.toString()));
                execStream.on('close', () => conn.end());
            });
        });
        stream.end(remoteScript);
    });
}).connect({ host: '72.61.162.106', port: 22, username: 'root', password: ';hdFJ6C1?YYc6FD8gdY2' });
