"use server";

import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { MetaAPI } from "@/lib/meta-api";
import Anthropic from "@anthropic-ai/sdk";
import { revalidatePath } from "next/cache";
import { logActivity } from "./activity";

const anthropic = new Anthropic();

export async function generateAutoReport(clientId: string, month: string) {
    const session = await getServerSession(authOptions);
    if (!session || (session.user.role !== "AM" && session.user.role !== "ADMIN")) {
        throw new Error("Unauthorized");
    }

    const client = await (prisma as any).client.findUnique({
        where: { id: clientId },
        include: {
            socialConnections: { where: { isActive: true } }
        }
    });

    if (!client) throw new Error("Client not found");
    if (session.user.role === "AM" && client.amId !== session.user.id) {
        throw new Error("Unauthorized Access");
    }

    // Check for duplicate report in same month
    const existing = await (prisma as any).report.findFirst({
        where: { clientId, month }
    });
    if (existing) {
        throw new Error(`DUPLICATE:${existing.id}`);
    }

    // --- Calculate exact date range for the selected month ---
    const [year, monthNum] = month.split("-").map(Number);
    const since = `${year}-${String(monthNum).padStart(2, "0")}-01`;
    const lastDay = new Date(year, monthNum, 0).getDate(); // last day of month
    const until = `${year}-${String(monthNum).padStart(2, "0")}-${lastDay}`;

    const sourcePlatforms: string[] = [];
    const campaignPlatforms: Record<string, any> = {};

    // --- Meta (Facebook + Instagram) ---
    const metaConnection = client.socialConnections?.find(
        (c: any) => c.platform === "FACEBOOK"
    );
    if (metaConnection) {
        try {
            const metaData = await fetchMetaData(metaConnection, since, until);
            if (metaData.facebook) {
                campaignPlatforms.facebook = metaData.facebook;
                sourcePlatforms.push("facebook");
            }
            if (metaData.instagram) {
                campaignPlatforms.instagram = metaData.instagram;
                sourcePlatforms.push("instagram");
            }
        } catch (e) {
            console.error("Auto report: Meta fetch error:", e);
        }
    }

    // --- Content Items from ActionPlan ---
    let contentItemsCount = 0;
    try {
        const actionPlan = await (prisma as any).actionPlan.findFirst({
            where: { clientId, month },
            include: {
                items: { where: { status: { in: ["APPROVED", "PUBLISHED"] } } }
            }
        });
        contentItemsCount = actionPlan?.items?.length || 0;
    } catch (e) {
        console.error("Auto report: ActionPlan fetch error:", e);
    }

    // --- ClientInsights (for AI summary context) ---
    const insights = await (prisma as any).clientInsight.findMany({
        where: { clientId },
        orderBy: { createdAt: "desc" },
        take: 3
    });

    // --- Previous Month Report (MoM context) ---
    const prevMonth =
        monthNum === 1
            ? `${year - 1}-12`
            : `${year}-${String(monthNum - 1).padStart(2, "0")}`;

    const prevReport = await (prisma as any).report.findFirst({
        where: { clientId, month: prevMonth }
    });
    const prevMetrics = prevReport?.metrics ? JSON.parse(prevReport.metrics) : null;

    // --- Build metrics object ---
    const metrics: any = {
        campaigns: [
            {
                id: "main",
                name: "الحملة الرئيسية",
                platforms: campaignPlatforms,
                linkedItems: []
            }
        ],
        emailMarketing: {
            campaigns: [{ name: "", emailsSent: 0, openRate: 0, clickRate: 0, unsubscribes: 0 }]
        },
        seo: {
            score: client.seoScore || 0,
            rank: "",
            notes: "",
            speed: 0,
            mobile: 0
        },
        summary: "",
        _autoGenerated: {
            generatedAt: new Date().toISOString(),
            sourcePlatforms,
            contentItemsCount
        }
    };

    // --- AI Summary ---
    try {
        metrics.summary = await generateAISummary(client, metrics, prevMetrics, insights, month);
    } catch (e) {
        console.error("Auto report: AI summary error:", e);
    }

    // --- Create the Draft Report ---
    const report = await (prisma as any).report.create({
        data: {
            clientId,
            month,
            metrics: JSON.stringify(metrics),
            status: "DRAFT"
        },
        include: { client: true }
    });

    await logActivity(
        `generated an auto report draft for ${report.client.name}`,
        "Report",
        report.id
    );

    revalidatePath("/am/reports");
    return { reportId: report.id };
}

// ---------------------------------------------------------------------------
// Meta data fetcher — fetches data for the exact month (since → until)
// ---------------------------------------------------------------------------
async function fetchMetaData(
    connection: any,
    since: string,
    until: string
): Promise<{ facebook?: any; instagram?: any }> {
    const meta = new MetaAPI(connection.accessToken);
    const result: { facebook?: any; instagram?: any } = {};

    // Helper: extract value from a page/ig insights response row.
    // Handles both time-series (values[]) and total_value formats.
    const sumDailyValues = (data: any[], metricName: string): number => {
        const row = data.find((r: any) => r.name === metricName);
        if (!row) return 0;
        // total_value format (Instagram metric_type=total_value)
        if (row.total_value !== undefined) {
            const tv = row.total_value;
            if (typeof tv.value === 'number') return tv.value;
            // follows_and_unfollows breakdown by follow_type:
            // NON_FOLLOWER = new follows (was not following, now following)
            // FOLLOWER = unfollows (was following, now not following)
            if (Array.isArray(tv.breakdowns?.[0]?.results)) {
                const followEntry = tv.breakdowns[0].results.find((r: any) => r.dimension_values?.includes('NON_FOLLOWER'));
                return Number(followEntry?.value) || 0;
            }
            return 0;
        }
        // time-series format (period=day values[])
        if (!row.values?.length) return 0;
        return row.values.reduce((acc: number, v: any) => {
            const val = v.value;
            if (typeof val === 'object' && val !== null) {
                return acc + (Number(val.follows) || Number(val.value) || 0);
            }
            return acc + (Number(val) || 0);
        }, 0);
    };

    const label = `[auto-report][${since}→${until}]`;

    // --- Fetch link clicks from ad account (FB + IG combined in one call) ---
    const adAccountId = connection.platformAccountId; // stored as act_XXXX
    let adLinkClicks = { facebook: 0, instagram: 0 };
    if (adAccountId) {
        try {
            adLinkClicks = await meta.getAdLinkClicksByPlatform(adAccountId, since, until);
            console.log(`${label} ad link_clicks:`, JSON.stringify(adLinkClicks));
        } catch (e: any) {
            console.error(`${label} ad link_clicks FAILED:`, e?.message || e);
        }
    }

    if (!connection.metadata) {
        console.warn(`${label} No metadata on connection — cannot get pageId`);
        return result;
    }

    let parsed: any = {};
    try { parsed = JSON.parse(connection.metadata); } catch (e) {
        console.error(`${label} Failed to parse connection.metadata:`, e);
        return result;
    }

    if (!parsed?.pageId) {
        console.warn(`${label} No pageId in metadata:`, parsed);
        return result;
    }

    const pageId = parsed.pageId;
    console.log(`${label} pageId=${pageId}`);

    // Page info — gets page access token + IG account
    let pageInfo: any = {};
    try {
        pageInfo = await meta.getPageInfo(pageId);
        console.log(`${label} pageInfo fan_count=${pageInfo?.fan_count}, ig=${pageInfo?.instagram_business_account?.id}`);
    } catch (e: any) {
        console.error(`${label} getPageInfo FAILED:`, e?.message || e);
    }

    const pageToken = pageInfo?.access_token;
    const igAccount = pageInfo?.instagram_business_account;

    if (!pageToken) {
        console.warn(`${label} No page access_token — page insights will be empty`);
    }

    // --- Facebook Page Insights ---
    // Metrics map to Business Manager: Views, Viewers, Content interactions, Visits, Follows
    let fbPageData: any[] = [];
    if (pageToken) {
        try {
            const pageInsights: any = await meta.getPageInsights(pageId, pageToken, since, until);
            fbPageData = pageInsights?.data || [];
            console.log(`${label} FB page metrics fetched:`, fbPageData.map((r: any) => `${r.name}=${r.values?.reduce((s: number, v: any) => s + (Number(v.value) || 0), 0)}`).join(', '));
        } catch (e: any) {
            console.error(`${label} FB page insights FAILED:`, e?.message || e);
            // Fallback: try with only the safe metrics if the full batch failed
            try {
                const fallback: any = await meta.getPageInsightsSafe(pageId, pageToken, since, until);
                fbPageData = fallback?.data || [];
                console.log(`${label} FB page insights (fallback) fetched:`, fbPageData.map((r: any) => r.name).join(', '));
            } catch (e2: any) {
                console.error(`${label} FB page insights fallback FAILED:`, e2?.message || e2);
            }
        }
    }

    result.facebook = {
        impressions: 0,                                                                  // page_impressions deprecated — unavailable in Meta API 2024+
        reach: sumDailyValues(fbPageData, "page_impressions_unique"),                   // Viewers
        engagement: sumDailyValues(fbPageData, "page_post_engagements"),                // Content interactions
        clicks: adLinkClicks.facebook,                                                   // Link clicks (ad account, facebook platform)
        spend: 0,
        profileVisits: sumDailyValues(fbPageData, "page_views_total"),                  // Visits
        followers: sumDailyValues(fbPageData, "page_fan_adds_by_paid_non_paid_unique"), // New follows
    };
    console.log(`${label} facebook result (pre-clicks):`, JSON.stringify(result.facebook));

    // --- Instagram (period=day, since IG doesn't support total_over_range) ---
    if (igAccount?.id && pageToken) {
        try {
            const igFollowers = igAccount.followers_count || 0;
            const igInsightsData: any = await meta.getIgInsights(igAccount.id, pageToken, since, until);
            const igInsights = igInsightsData?.data || [];
            console.log(`${label} IG metrics fetched:`, igInsights.map((r: any) => `${r.name}=${r.values?.reduce((s: number, v: any) => s + (v.value || 0), 0)}`).join(', '));

            // Log raw follows_and_unfollows to debug parsing
            const followsRow = igInsights.find((r: any) => r.name === "follows_and_unfollows");
            console.log(`${label} follows_and_unfollows raw:`, JSON.stringify(followsRow?.total_value || followsRow?.values?.[0]));

            result.instagram = {
                views: sumDailyValues(igInsights, "views"),                    // Views (total_value)
                reach: sumDailyValues(igInsights, "reach"),                    // Reach
                engagement: sumDailyValues(igInsights, "total_interactions"),  // Content interactions
                clicks: adLinkClicks.instagram || sumDailyValues(igInsights, "website_clicks"), // Link clicks (ad account, fallback to bio)
                profileVisits: sumDailyValues(igInsights, "profile_views"),    // Profile Visits
                followers: sumDailyValues(igInsights, "follows_and_unfollows"), // New follows only
            };
            console.log(`${label} instagram result:`, JSON.stringify(result.instagram));
        } catch (e: any) {
            console.error(`${label} Instagram insights FAILED:`, e?.message || e);
        }
    } else {
        console.warn(`${label} No IG account or no pageToken — skipping Instagram insights`);
    }

    return result;
}

// ---------------------------------------------------------------------------
// AI Summary generator
// ---------------------------------------------------------------------------
async function generateAISummary(
    client: any,
    metrics: any,
    prevMetrics: any | null,
    insights: any[],
    month: string
): Promise<string> {
    const fbData = metrics.campaigns[0]?.platforms?.facebook;
    const igData = metrics.campaigns[0]?.platforms?.instagram;
    const sourcePlatforms: string[] = metrics._autoGenerated?.sourcePlatforms || [];

    const prevFb = prevMetrics?.campaigns?.[0]?.platforms?.facebook;
    const prevIg = prevMetrics?.campaigns?.[0]?.platforms?.instagram;

    const mom = (curr: number, prev: number | undefined) =>
        prev && prev > 0 ? `${curr > prev ? "+" : ""}${Math.round(((curr - prev) / prev) * 100)}%` : null;

    const fbReachMom = fbData && prevFb ? mom(fbData.reach, prevFb.reach) : null;
    const igReachMom = igData && prevIg ? mom(igData.reach, prevIg.reach) : null;

    // Gather latest industry insight if available
    const industryInsight = insights.find((i: any) => i.type === "INDUSTRY");
    let industryContext = "";
    if (industryInsight) {
        try {
            const items = JSON.parse(industryInsight.content);
            const top = items[0];
            if (top) industryContext = `Recent industry trend: ${top.titleEn} — ${top.summaryEn}`;
        } catch (e) { }
    }

    const prompt = `You are a senior digital marketing analyst writing a professional monthly performance summary for an agency client report.

Client: ${client.name}
Industry: ${client.industry || "General"}
Month: ${month}
Connected Platforms: ${sourcePlatforms.join(", ") || "None"}

Performance Data:
${fbData ? `• Facebook — Views: ${fbData.impressions?.toLocaleString()}, Viewers: ${fbData.reach?.toLocaleString()}, Content Interactions: ${fbData.engagement?.toLocaleString()}, Link Clicks: ${fbData.clicks?.toLocaleString()}, Visits: ${fbData.profileVisits?.toLocaleString()}, New Follows: ${fbData.followers?.toLocaleString()}${fbReachMom ? `, Reach MoM: ${fbReachMom}` : ""}` : ""}
${igData ? `• Instagram — Views: ${igData.views?.toLocaleString()}, Reach: ${igData.reach?.toLocaleString()}, Content Interactions: ${igData.engagement?.toLocaleString()}, Link Clicks: ${igData.clicks?.toLocaleString()}, Profile Visits: ${igData.profileVisits?.toLocaleString()}, New Follows: ${igData.followers?.toLocaleString()}${igReachMom ? `, Reach MoM: ${igReachMom}` : ""}` : ""}
${industryContext ? `\nMarket Context: ${industryContext}` : ""}

Write a concise, professional bilingual summary (3-4 sentences each).
Respond ONLY with valid JSON — no markdown, no explanation:
{
  "ar": "ملخص احترافي بالعربية (3-4 جمل موجزة واضحة)",
  "en": "Professional summary in English (3-4 concise sentences)"
}`;

    const response = await anthropic.messages.create({
        model: "claude-sonnet-4-6",
        max_tokens: 1200,
        messages: [{ role: "user", content: prompt }]
    });

    const text = (response.content[0] as any).text.trim();
    const parsed = JSON.parse(text);
    return `${parsed.ar}\n\n${parsed.en}`;
}
