"use server";

import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { MetaAPI } from "@/lib/meta-api";
import Anthropic from "@anthropic-ai/sdk";
import { revalidatePath } from "next/cache";
import { logActivity } from "./activity";

const anthropic = new Anthropic();

export async function generateAutoReport(clientId: string, month: string) {
    const session = await getServerSession(authOptions);
    if (!session || (session.user.role !== "AM" && session.user.role !== "ADMIN")) {
        throw new Error("Unauthorized");
    }

    const client = await (prisma as any).client.findUnique({
        where: { id: clientId },
        include: {
            socialConnections: { where: { isActive: true } }
        }
    });

    if (!client) throw new Error("Client not found");
    if (session.user.role === "AM" && client.amId !== session.user.id) {
        throw new Error("Unauthorized Access");
    }

    // Check for duplicate report in same month
    const existing = await (prisma as any).report.findFirst({
        where: { clientId, month }
    });
    if (existing) {
        throw new Error(`DUPLICATE:${existing.id}`);
    }

    // --- Calculate exact date range for the selected month ---
    const [year, monthNum] = month.split("-").map(Number);
    const since = `${year}-${String(monthNum).padStart(2, "0")}-01`;
    const lastDay = new Date(year, monthNum, 0).getDate(); // last day of month
    const until = `${year}-${String(monthNum).padStart(2, "0")}-${lastDay}`;

    const sourcePlatforms: string[] = [];
    const campaignPlatforms: Record<string, any> = {};

    // --- Meta (Facebook + Instagram) ---
    const metaConnection = client.socialConnections?.find(
        (c: any) => c.platform === "FACEBOOK"
    );
    if (metaConnection) {
        try {
            const metaData = await fetchMetaData(metaConnection, since, until);
            if (metaData.facebook) {
                campaignPlatforms.facebook = metaData.facebook;
                sourcePlatforms.push("facebook");
            }
            if (metaData.instagram) {
                campaignPlatforms.instagram = metaData.instagram;
                sourcePlatforms.push("instagram");
            }
        } catch (e) {
            console.error("Auto report: Meta fetch error:", e);
        }
    }

    // --- Content Items from ActionPlan ---
    let contentItemsCount = 0;
    try {
        const actionPlan = await (prisma as any).actionPlan.findFirst({
            where: { clientId, month },
            include: {
                items: { where: { status: { in: ["APPROVED", "PUBLISHED"] } } }
            }
        });
        contentItemsCount = actionPlan?.items?.length || 0;
    } catch (e) {
        console.error("Auto report: ActionPlan fetch error:", e);
    }

    // --- ClientInsights (for AI summary context) ---
    const insights = await (prisma as any).clientInsight.findMany({
        where: { clientId },
        orderBy: { createdAt: "desc" },
        take: 3
    });

    // --- Previous Month Report (MoM context) ---
    const prevMonth =
        monthNum === 1
            ? `${year - 1}-12`
            : `${year}-${String(monthNum - 1).padStart(2, "0")}`;

    const prevReport = await (prisma as any).report.findFirst({
        where: { clientId, month: prevMonth }
    });
    const prevMetrics = prevReport?.metrics ? JSON.parse(prevReport.metrics) : null;

    // --- Build metrics object ---
    const metrics: any = {
        campaigns: [
            {
                id: "main",
                name: "الحملة الرئيسية",
                platforms: campaignPlatforms,
                linkedItems: []
            }
        ],
        emailMarketing: {
            campaigns: [{ name: "", emailsSent: 0, openRate: 0, clickRate: 0, unsubscribes: 0 }]
        },
        seo: {
            score: client.seoScore || 0,
            rank: "",
            notes: "",
            speed: 0,
            mobile: 0
        },
        summary: "",
        _autoGenerated: {
            generatedAt: new Date().toISOString(),
            sourcePlatforms,
            contentItemsCount
        }
    };

    // --- AI Summary ---
    try {
        metrics.summary = await generateAISummary(client, metrics, prevMetrics, insights, month);
    } catch (e) {
        console.error("Auto report: AI summary error:", e);
    }

    // --- Create the Draft Report ---
    const report = await (prisma as any).report.create({
        data: {
            clientId,
            month,
            metrics: JSON.stringify(metrics),
            status: "DRAFT"
        },
        include: { client: true }
    });

    await logActivity(
        `generated an auto report draft for ${report.client.name}`,
        "Report",
        report.id
    );

    revalidatePath("/am/reports");
    return { reportId: report.id };
}

// ---------------------------------------------------------------------------
// Meta data fetcher — fetches data for the exact month (since → until)
// ---------------------------------------------------------------------------
async function fetchMetaData(
    connection: any,
    since: string,
    until: string
): Promise<{ facebook?: any; instagram?: any }> {
    const meta = new MetaAPI(connection.accessToken);
    const result: { facebook?: any; instagram?: any } = {};

    // Helper: sum all daily values from a page/ig insights response
    const sumDailyValues = (data: any[], metricName: string): number => {
        const row = data.find((r: any) => r.name === metricName);
        if (!row?.values?.length) return 0;
        return row.values.reduce((acc: number, v: any) => acc + (Number(v.value) || 0), 0);
    };

    // --- Ad Account (Paid) ---
    let adInsights: any = {};
    try {
        const res: any = await meta.getAdAccountInsights(
            connection.platformAccountId, 'last_30d', since, until
        );
        adInsights = res?.data?.[0] || {};
    } catch (e) {
        console.error("Auto report: Ad insights error:", e);
    }

    if (!connection.metadata) return result;

    try {
        const parsed = JSON.parse(connection.metadata);
        if (!parsed?.pageId) return result;

        const pageId = parsed.pageId;

        // Page info (fan_count + page token + IG account)
        let pageInfo: any = {};
        try { pageInfo = await meta.getPageInfo(pageId); } catch (e) { }

        const pageToken = pageInfo?.access_token;
        const igAccount = pageInfo?.instagram_business_account;

        // --- Facebook Organic (daily values summed for the month) ---
        let fbReach = 0;
        let fbEngagement = 0;

        if (pageToken) {
            try {
                const pageInsights: any = await meta.getPageInsights(pageId, pageToken, since, until);
                const data = pageInsights?.data || [];
                fbReach = sumDailyValues(data, "page_impressions_unique");
                fbEngagement = sumDailyValues(data, "page_post_engagements");
            } catch (e) {
                console.error("Auto report: FB page insights error:", e);
            }
        }

        result.facebook = {
            impressions: Number(adInsights.impressions) || 0,
            reach: fbReach,
            engagement: fbEngagement,
            clicks: Number(adInsights.clicks) || 0,
            profileVisits: pageInfo?.fan_count || 0, // total page likes (snapshot)
            followers: 0
        };

        // --- Instagram ---
        if (igAccount?.id && pageToken) {
            try {
                const igFollowers = igAccount.followers_count || 0;

                // Reach (daily values summed)
                const igReachData: any = await meta.getIgReach(igAccount.id, pageToken, since, until);
                const igReach = sumDailyValues(igReachData?.data || [], "reach");

                // Media (filtered to the month via since/until)
                const igMedia: any = await meta.getIgMediaInsights(igAccount.id, pageToken, since, until);
                const mediaList = igMedia?.data || [];
                let sumViews = 0;
                let sumEngagement = 0;
                mediaList.forEach((m: any) => {
                    sumViews += m.video_views || 0;
                    sumEngagement += (m.like_count || 0) + (m.comments_count || 0);
                });
                // Fallback: if no video views (Reels), estimate from reach
                if (sumViews === 0 && igReach > 0) sumViews = Math.floor(igReach * 0.95);

                result.instagram = {
                    views: sumViews,
                    reach: igReach,
                    engagement: sumEngagement,
                    clicks: 0,
                    profileVisits: 0,
                    followers: igFollowers
                };
            } catch (e) {
                console.error("Auto report: Instagram insights error:", e);
            }
        }
    } catch (e) {
        console.error("Auto report: Organic data error:", e);
    }

    return result;
}

// ---------------------------------------------------------------------------
// AI Summary generator
// ---------------------------------------------------------------------------
async function generateAISummary(
    client: any,
    metrics: any,
    prevMetrics: any | null,
    insights: any[],
    month: string
): Promise<string> {
    const fbData = metrics.campaigns[0]?.platforms?.facebook;
    const igData = metrics.campaigns[0]?.platforms?.instagram;
    const sourcePlatforms: string[] = metrics._autoGenerated?.sourcePlatforms || [];

    const prevFb = prevMetrics?.campaigns?.[0]?.platforms?.facebook;
    const prevIg = prevMetrics?.campaigns?.[0]?.platforms?.instagram;

    const mom = (curr: number, prev: number | undefined) =>
        prev && prev > 0 ? `${curr > prev ? "+" : ""}${Math.round(((curr - prev) / prev) * 100)}%` : null;

    const fbReachMom = fbData && prevFb ? mom(fbData.reach, prevFb.reach) : null;
    const igReachMom = igData && prevIg ? mom(igData.reach, prevIg.reach) : null;

    // Gather latest industry insight if available
    const industryInsight = insights.find((i: any) => i.type === "INDUSTRY");
    let industryContext = "";
    if (industryInsight) {
        try {
            const items = JSON.parse(industryInsight.content);
            const top = items[0];
            if (top) industryContext = `Recent industry trend: ${top.titleEn} — ${top.summaryEn}`;
        } catch (e) { }
    }

    const prompt = `You are a senior digital marketing analyst writing a professional monthly performance summary for an agency client report.

Client: ${client.name}
Industry: ${client.industry || "General"}
Month: ${month}
Connected Platforms: ${sourcePlatforms.join(", ") || "None"}

Performance Data:
${fbData ? `• Facebook — Reach: ${fbData.reach?.toLocaleString()}, Engagement: ${fbData.engagement?.toLocaleString()}, Impressions: ${fbData.impressions?.toLocaleString()}, Clicks: ${fbData.clicks?.toLocaleString()}${fbReachMom ? `, Reach MoM: ${fbReachMom}` : ""}` : ""}
${igData ? `• Instagram — Reach: ${igData.reach?.toLocaleString()}, Views: ${igData.views?.toLocaleString()}, Engagement: ${igData.engagement?.toLocaleString()}, Followers: ${igData.followers?.toLocaleString()}${igReachMom ? `, Reach MoM: ${igReachMom}` : ""}` : ""}
${industryContext ? `\nMarket Context: ${industryContext}` : ""}

Write a concise, professional bilingual summary (3-4 sentences each).
Respond ONLY with valid JSON — no markdown, no explanation:
{
  "ar": "ملخص احترافي بالعربية (3-4 جمل موجزة واضحة)",
  "en": "Professional summary in English (3-4 concise sentences)"
}`;

    const response = await anthropic.messages.create({
        model: "claude-sonnet-4-6",
        max_tokens: 700,
        messages: [{ role: "user", content: prompt }]
    });

    const text = (response.content[0] as any).text.trim();
    const parsed = JSON.parse(text);
    return `${parsed.ar}\n\n${parsed.en}`;
}
